all: UI.class Hotel.class Receptionist.class Guest.class Main.class

UI.class: UI.java
	javac UI.java

Hotel.class: Hotel.java
	javac Hotel.java

Receptionist.class: Receptionist.java
	javac Receptionist.java

Guest.class: Guest.java
	javac Guest.java

Main.class: Main.java
	javac Main.java

run:
	java Main
		
clean:
	rm -f *.class
