all: Interface.class Library.class Staff.class User.class Main.class

Interface.class: Interface.java
	javac Interface.java

Library.class: Library.java
	javac Library.java

Staff.class: Staff.java
	javac Staff.java 

User.class: User.java
	javac User.java

Main.class: Main.java
	javac Main.java

run:
	java Main
		
clean:
	rm -f *.class
