all: myAbstractCollection.class SingleLinkedList.class myStringBuilder.class main.class

myAbstractCollection.class: myAbstractCollection.java
	javac myAbstractCollection.java

SingleLinkedList.class: SingleLinkedList.java
	javac SingleLinkedList.java

myStringBuilder.class: myStringBuilder.java
	javac myStringBuilder.java

main.class: main.java
	javac main.java

run:
	java main
		
clean:
	rm -f *.class
