all: Course.class GTU_Courses_P1.class ExtendLinkedList_P2.class CustomLinkedList_P3.class Main.class

Course.class: Course.java
	javac Course.java

GTU_Courses_P1.class: GTU_Courses_P1.java
	javac GTU_Courses_P1.java

ExtendLinkedList_P2.class: ExtendLinkedList_P2.java
	javac ExtendLinkedList_P2.java

CustomLinkedList_P3.class: CustomLinkedList_P3.java
	javac CustomLinkedList_P3.java

Main.class: Main.java
	javac Main.java

run:
	java Main
		
clean:
	rm -f *.class
